# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Multi(object):
    def setupUi(self, Multi):
        Multi.setObjectName("Multi")
        Multi.resize(1048, 715)
        self.tableView = QtWidgets.QTableView(Multi)
        self.tableView.setGeometry(QtCore.QRect(20, 210, 1001, 251))
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(Multi)
        self.label.setGeometry(QtCore.QRect(30, 490, 51, 16))
        self.label.setObjectName("label")
        self.memory = QtWidgets.QSpinBox(Multi)
        self.memory.setGeometry(QtCore.QRect(90, 480, 51, 31))
        self.memory.setAlignment(QtCore.Qt.AlignCenter)
        self.memory.setMaximum(9000)
        self.memory.setProperty("value", 100)
        self.memory.setObjectName("memory")
        self.label_2 = QtWidgets.QLabel(Multi)
        self.label_2.setGeometry(QtCore.QRect(170, 490, 61, 16))
        self.label_2.setObjectName("label_2")
        self.machine = QtWidgets.QSpinBox(Multi)
        self.machine.setGeometry(QtCore.QRect(240, 480, 51, 31))
        self.machine.setAlignment(QtCore.Qt.AlignCenter)
        self.machine.setProperty("value", 4)
        self.machine.setObjectName("machine")
        self.label_3 = QtWidgets.QLabel(Multi)
        self.label_3.setGeometry(QtCore.QRect(320, 480, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.average = QtWidgets.QLineEdit(Multi)
        self.average.setGeometry(QtCore.QRect(460, 480, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.average.setFont(font)
        self.average.setObjectName("average")
        self.label_4 = QtWidgets.QLabel(Multi)
        self.label_4.setGeometry(QtCore.QRect(600, 480, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.average2 = QtWidgets.QLineEdit(Multi)
        self.average2.setGeometry(QtCore.QRect(790, 480, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.average2.setFont(font)
        self.average2.setObjectName("average2")
        self.groupBox = QtWidgets.QGroupBox(Multi)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 371, 171))
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(80, 30, 141, 31))
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber.setObjectName("lcdNumber")
        self.groupBox_2 = QtWidgets.QGroupBox(Multi)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 30, 101, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.default_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.default_2.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.default_2.setObjectName("default_2")
        self.add = QtWidgets.QPushButton(self.groupBox_2)
        self.add.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.add.setObjectName("add")
        self.groupBox_3 = QtWidgets.QGroupBox(Multi)
        self.groupBox_3.setGeometry(QtCore.QRect(490, 30, 121, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.reset = QtWidgets.QPushButton(self.groupBox_3)
        self.reset.setGeometry(QtCore.QRect(30, 70, 75, 23))
        self.reset.setObjectName("reset")
        self.quit = QtWidgets.QPushButton(self.groupBox_3)
        self.quit.setGeometry(QtCore.QRect(30, 110, 75, 23))
        self.quit.setObjectName("quit")
        self.groupBox_4 = QtWidgets.QGroupBox(Multi)
        self.groupBox_4.setGeometry(QtCore.QRect(830, 520, 191, 181))
        self.groupBox_4.setObjectName("groupBox_4")
        self.memoryarr = QtWidgets.QTableView(self.groupBox_4)
        self.memoryarr.setGeometry(QtCore.QRect(20, 30, 151, 121))
        self.memoryarr.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.memoryarr.setObjectName("memoryarr")
        self.memoryarr.horizontalHeader().setDefaultSectionSize(80)
        self.groupBox_5 = QtWidgets.QGroupBox(Multi)
        self.groupBox_5.setGeometry(QtCore.QRect(610, 30, 411, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.outer = QtWidgets.QTableView(self.groupBox_5)
        self.outer.setGeometry(QtCore.QRect(30, 30, 341, 121))
        self.outer.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.outer.setObjectName("outer")
        self.groupBox_7 = QtWidgets.QGroupBox(Multi)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 520, 411, 181))
        self.groupBox_7.setObjectName("groupBox_7")
        self.mj = QtWidgets.QTableView(self.groupBox_7)
        self.mj.setGeometry(QtCore.QRect(30, 30, 341, 121))
        self.mj.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mj.setObjectName("mj")
        self.groupBox_6 = QtWidgets.QGroupBox(Multi)
        self.groupBox_6.setGeometry(QtCore.QRect(420, 520, 411, 181))
        self.groupBox_6.setObjectName("groupBox_6")
        self.run = QtWidgets.QTableView(self.groupBox_6)
        self.run.setGeometry(QtCore.QRect(30, 30, 341, 121))
        self.run.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.run.setObjectName("run")

        self.retranslateUi(Multi)
        QtCore.QMetaObject.connectSlotsByName(Multi)

    def retranslateUi(self, Multi):
        _translate = QtCore.QCoreApplication.translate
        Multi.setWindowTitle(_translate("Multi", "Form"))
        self.label.setText(_translate("Multi", "可用内存"))
        self.label_2.setText(_translate("Multi", "磁带机个数"))
        self.label_3.setText(_translate("Multi", "平均周转时间"))
        self.label_4.setText(_translate("Multi", "平均带权周转时间"))
        self.groupBox.setTitle(_translate("Multi", "调度信息"))
        self.label_5.setText(_translate("Multi", "作业调度：先来先服务算法"))
        self.label_6.setText(_translate("Multi", "进程调度：可抢占的最短进程优先算法"))
        self.label_7.setText(_translate("Multi", "时间："))
        self.groupBox_2.setTitle(_translate("Multi", "作业功能"))
        self.default_2.setText(_translate("Multi", "默认"))
        self.add.setText(_translate("Multi", "添加"))
        self.groupBox_3.setTitle(_translate("Multi", "功能"))
        self.pushButton.setText(_translate("Multi", "执行"))
        self.reset.setText(_translate("Multi", "重置"))
        self.quit.setText(_translate("Multi", "退出"))
        self.groupBox_4.setTitle(_translate("Multi", "内存空闲分区情况"))
        self.groupBox_5.setTitle(_translate("Multi", "外存情况"))
        self.groupBox_7.setTitle(_translate("Multi", "内存中作业情况"))
        self.groupBox_6.setTitle(_translate("Multi", "正在运行情况"))

